pipeline {
    agent any

    stages {
        stage('Pull Code') {
            steps {
                cleanWs()
                echo 'Pull Code'
            }
        }
        stage('Download Dependencies') {
            steps {
                echo 'Download Dependencies'
            }
        }
        stage('Unit Test') {
            steps {
                echo 'Unit Test'
            }
        }
        stage('Component Test') {
            steps {
                echo 'Component Test'
            }
        }

        stage('E2E test') {
            steps {
                echo 'E2E test'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy'
                /*withCredentials([string(credentialsId: 'team2-backend-docker', variable: 'team2sshPass')]) {
                    script {
                        def remote = [:]
                        remote.host = '159.223.45.216'
                        remote.name = 'team2-ssh'
                        remote.user = 'root'
                        remote.password = "${team2sshPass}"
                        remote.allowAnyHosts = true

                        sshCommand remote: remote, command: "git clone https://github.com/trabnm1313/SDTP.git"
                        sshCommand remote: remote, command: "docker-compose -f SDTP/dockerCompose.yml up -d"
                        sshCommand remote: remote, command: "rm -r SDTP"
                    }
                }*/
            }
        }
        stage('Notification') {
            steps {
                echo 'OK'
            }
        }
    }
}
